//! rmcp 1.5 server wiring — SPEC §2 architecture + §3.4 `isError` mapping.
//!
//! [`BlastGuardServer`] holds shared state (graph, session, config) behind
//! `Arc<Mutex<_>>` so it can be cheaply cloned across tool-handler futures.
//! The [`ServerHandler`] impl wires `#[tool]` adapters and the
//! `blastguard://status` resource (Tasks 3-6).
//!
//! [`run`] is the async boot entry called from `main.rs` via
//! `tokio::runtime::Runtime::block_on`.

use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};

use anyhow::Context;
use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::handler::server::wrapper::{Json, Parameters};
use rmcp::model::{
    CallToolResult, Implementation, ServerCapabilities, ServerInfo,
};
use rmcp::{tool, tool_handler, tool_router};
use rmcp::handler::server::ServerHandler;
use rmcp::service::ServiceExt as _;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use crate::config::Config;
use crate::graph::CodeGraph;
use crate::index::indexer;
use crate::mcp::adapters::to_error_result;
use crate::search::dispatch;
use crate::session::SessionState;

// ── DTOs ─────────────────────────────────────────────────────────────────────

/// Input to the `search` MCP tool.
#[derive(Debug, Clone, Deserialize, Serialize, JsonSchema)]
pub struct SearchRequest {
    pub query: String,
    /// Phase 2: optional glob to narrow the search. Ignored in Phase 1.
    #[serde(default)]
    pub scope: Option<String>,
}

/// Output from the `search` tool.
#[derive(Debug, Clone, Serialize, JsonSchema)]
pub struct SearchResponse {
    pub hits: Vec<String>,
}

// ── BlastGuardServer ────────────────────────────────────────────────────────

/// Shared server state. Cheap to clone — all heavy data lives behind `Arc`.
///
/// Constructed once in [`run`] and passed directly to `serve()`. Tool handlers
/// receive a clone of this struct per-call via rmcp's dispatch machinery.
#[derive(Clone)]
pub struct BlastGuardServer {
    /// In-memory code graph, rebuilt from cache on warm start.
    pub(crate) graph: Arc<Mutex<CodeGraph>>,
    /// Per-session mutable state: edited files, last test run, etc.
    pub(crate) session: Arc<Mutex<SessionState>>,
    /// Absolute path to the project root passed on the command line.
    pub(crate) project_root: PathBuf,
    /// Project configuration loaded from `.blastguard/config.toml`.
    // `config` is carried for future tool handlers that need per-project settings.
    #[expect(dead_code, reason = "future tool handlers will read per-project config")]
    pub(crate) config: Arc<Config>,
    /// Generated by `#[tool_router]` — routes `call_tool` to the correct handler.
    // The macro-generated `call_tool` and `list_tools` methods access this field;
    // the static analyser cannot see macro-generated call sites.
    #[expect(dead_code, reason = "accessed by macro-generated call_tool / list_tools")]
    pub(crate) tool_router: ToolRouter<BlastGuardServer>,
}

impl BlastGuardServer {
    /// Construct a new server, wrapping `graph` and a fresh [`SessionState`]
    /// in `Arc<Mutex<_>>` for shared ownership across async handlers.
    ///
    /// `config` is wrapped in `Arc` here so callers don't need to.
    #[must_use]
    pub fn new(graph: CodeGraph, project_root: PathBuf, config: Config) -> Self {
        Self {
            graph: Arc::new(Mutex::new(graph)),
            session: Arc::new(Mutex::new(SessionState::new())),
            project_root,
            config: Arc::new(config),
            tool_router: Self::tool_router(),
        }
    }
}

// ── Tool handlers ─────────────────────────────────────────────────────────────

#[tool_router]
impl BlastGuardServer {
    /// Dispatch a search query to the AST graph or regex grep backend.
    ///
    /// # Errors
    ///
    /// Always returns `Ok` — this handler has no fallible path in Phase 1.
    /// Error variants are reserved for Phase 2 semantic search.
    ///
    /// # Panics
    ///
    /// Panics if the graph `Mutex` is poisoned by a prior thread panic.
    #[tool(
        name = "search",
        description = "Search the codebase via AST dependency graph or regex grep. \
Structural queries ('callers of X', 'tests for FILE') resolve instantly with inline \
signatures. Free-text falls through to grep. Returns up to 30 hits.",
        annotations(
            read_only_hint = true,
            destructive_hint = false,
            idempotent_hint = true,
            open_world_hint = false
        )
    )]
    pub fn search_tool(
        &self,
        Parameters(req): Parameters<SearchRequest>,
    ) -> Result<Json<SearchResponse>, CallToolResult> {
        let graph = self.graph.lock().expect("graph lock poisoned");
        let hits = dispatch(&graph, &self.project_root, &req.query);
        let lines: Vec<String> = hits
            .iter()
            .map(|h| match (&h.signature, &h.snippet) {
                (Some(sig), _) => format!("{}:{} \u{2014} {}", h.file.display(), h.line, sig),
                (None, Some(snip)) => {
                    format!("{}:{} \u{2014} {}", h.file.display(), h.line, snip.trim())
                }
                (None, None) => format!("{}:{}", h.file.display(), h.line),
            })
            .collect();
        Ok(Json(SearchResponse { hits: lines }))
    }

    /// Apply text replacements to a file on disk, returning cascade warnings and bundled context.
    ///
    /// # Errors
    ///
    /// Returns a `CallToolResult` with `is_error: true` when the edit fails
    /// (ambiguous match, edit not found, I/O error, or parse failure). The
    /// `content` block carries the `BlastGuardError::Display` string.
    #[tool(
        name = "apply_change",
        description = "Edit files with impact analysis. Writes immediately — no approval \
gate. Response includes cascade warnings (callers that may break, interfaces that \
may be violated) and a context bundle (callers, tests) so you rarely need follow-up \
searches. Use for multi-file changes where blast radius matters; for trivial \
single-line fixes your native edit tool is fine.",
        annotations(
            read_only_hint = false,
            destructive_hint = true,
            idempotent_hint = false,
            open_world_hint = false
        )
    )]
    pub fn apply_change_tool(
        &self,
        Parameters(req): Parameters<crate::edit::ApplyChangeRequest>,
    ) -> Result<Json<crate::edit::ApplyChangeResponse>, CallToolResult> {
        match crate::mcp::apply_change::handle(
            &self.graph,
            &self.session,
            &self.project_root,
            &req,
        ) {
            Ok(resp) => Ok(Json(resp)),
            Err(err) => Err(to_error_result(&err)),
        }
    }
}

// ── ServerHandler impl ────────────────────────────────────────────────────────

/// `#[tool_handler]` generates `call_tool` + `list_tools` methods that
/// delegate to `self.tool_router`.
#[tool_handler]
impl ServerHandler for BlastGuardServer {
    /// Advertise the server identity and capabilities to connecting clients.
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(
            ServerCapabilities::builder()
                .enable_tools()
                .build(),
        )
        .with_server_info(Implementation::new(
            env!("CARGO_PKG_NAME"),
            env!("CARGO_PKG_VERSION"),
        ))
        .with_instructions(
            "BlastGuard: AST graph search, cascade-aware edits, and test-failure \
             attribution for AI coding agents. Tools: search, apply_change, run_tests.",
        )
    }
}

// ── Boot entry point ─────────────────────────────────────────────────────────

/// Async boot entry: load config, warm-start the index, stand up the rmcp
/// stdio server, and block until the MCP client disconnects.
///
/// # Errors
///
/// Propagates config load, indexer warm-start, or MCP handshake failures.
pub async fn run(project_root: &Path) -> anyhow::Result<()> {
    let config = Config::load(project_root).context("loading .blastguard/config.toml")?;

    let graph = indexer::warm_start(project_root).context("warm-starting index")?;

    let server = BlastGuardServer::new(graph, project_root.to_path_buf(), config);

    tracing::info!(
        project_root = %project_root.display(),
        version = env!("CARGO_PKG_VERSION"),
        "BlastGuard MCP server starting on stdio"
    );

    let transport = rmcp::transport::io::stdio();

    let service = server
        .serve(transport)
        .await
        .context("rmcp server initialization failed")?;

    tracing::info!("BlastGuard MCP server ready — awaiting client requests");

    service
        .waiting()
        .await
        .context("MCP service terminated with error")?;

    tracing::info!("BlastGuard MCP server shutting down cleanly");
    Ok(())
}
