//! rmcp 1.5 server wiring — SPEC §2 architecture + §3.4 `isError` mapping.
//!
//! [`BlastGuardServer`] holds shared state (graph, session, config) behind
//! `Arc<Mutex<_>>` so it can be cheaply cloned across tool-handler futures.
//! The [`ServerHandler`] impl wires `#[tool]` adapters and the
//! `blastguard://status` resource (Tasks 3-6).
//!
//! [`run`] is the async boot entry called from `main.rs` via
//! `tokio::runtime::Runtime::block_on`.

use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};

use anyhow::Context;
use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::handler::server::wrapper::{Json, Parameters};
use rmcp::handler::server::ServerHandler;
use rmcp::model::{
    AnnotateAble as _, CallToolResult, Implementation, ListResourcesResult, PaginatedRequestParams,
    RawResource, ReadResourceRequestParams, ReadResourceResult, ResourceContents,
    ServerCapabilities, ServerInfo,
};
use rmcp::service::RequestContext;
use rmcp::service::ServiceExt as _;
use rmcp::{tool, tool_handler, tool_router, ErrorData, RoleServer};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use crate::config::Config;
use crate::graph::CodeGraph;
use crate::index::indexer;
use crate::mcp::adapters::to_error_result;
use crate::search::dispatch;
use crate::session::SessionState;

// ── DTOs ─────────────────────────────────────────────────────────────────────

/// Input to the `search` MCP tool.
#[derive(Debug, Clone, Deserialize, Serialize, JsonSchema)]
pub struct SearchRequest {
    pub query: String,
    /// Phase 2: optional glob to narrow the search. Ignored in Phase 1.
    #[serde(default)]
    pub scope: Option<String>,
}

/// Output from the `search` tool.
#[derive(Debug, Clone, Serialize, JsonSchema)]
pub struct SearchResponse {
    pub hits: Vec<String>,
}

// ── BlastGuardServer ────────────────────────────────────────────────────────

/// Shared server state. Cheap to clone — all heavy data lives behind `Arc`.
///
/// Constructed once in [`run`] and passed directly to `serve()`. Tool handlers
/// receive a clone of this struct per-call via rmcp's dispatch machinery.
#[derive(Clone)]
pub struct BlastGuardServer {
    /// In-memory code graph, rebuilt from cache on warm start.
    pub(crate) graph: Arc<Mutex<CodeGraph>>,
    /// Per-session mutable state: edited files, last test run, etc.
    pub(crate) session: Arc<Mutex<SessionState>>,
    /// Absolute path to the project root passed on the command line.
    pub(crate) project_root: PathBuf,
    /// Project configuration loaded from `.blastguard/config.toml`.
    // `config` is carried for future tool handlers that need per-project settings.
    #[expect(
        dead_code,
        reason = "future tool handlers will read per-project config"
    )]
    pub(crate) config: Arc<Config>,
    /// Generated by `#[tool_router]` — routes `call_tool` to the correct handler.
    // The macro-generated `call_tool` and `list_tools` methods access this field;
    // the static analyser cannot see macro-generated call sites.
    #[expect(
        dead_code,
        reason = "accessed by macro-generated call_tool / list_tools"
    )]
    pub(crate) tool_router: ToolRouter<BlastGuardServer>,
}

impl BlastGuardServer {
    /// Construct a new server, wrapping `graph` and a fresh [`SessionState`]
    /// in `Arc<Mutex<_>>` for shared ownership across async handlers.
    ///
    /// `config` is wrapped in `Arc` here so callers don't need to.
    #[must_use]
    pub fn new(graph: CodeGraph, project_root: PathBuf, config: Config) -> Self {
        Self {
            graph: Arc::new(Mutex::new(graph)),
            session: Arc::new(Mutex::new(SessionState::new())),
            project_root,
            config: Arc::new(config),
            tool_router: Self::tool_router(),
        }
    }
}

// ── Tool handlers ─────────────────────────────────────────────────────────────

#[tool_router]
impl BlastGuardServer {
    /// Query the project's AST code graph.
    ///
    /// Phase 1 supports: `outline of PATH` (all symbols in a file),
    /// `find NAME` (fuzzy symbol lookup), `exports of PATH` (public symbols),
    /// `libraries` (external/internal package list), `callers of NAME`
    /// (same-file only), and `grep <pattern>` fallback.
    ///
    /// Returns 50-300 tokens of structured graph data instead of 10K+ from raw
    /// grep. Prefer this over native Grep for structural queries; use Grep for
    /// free-text search across files.
    #[tool(
        name = "search",
        description = "Query the project's AST code graph. \
Phase 1 supports: `outline of PATH` (all symbols in a file), \
`find NAME` (fuzzy symbol lookup), `exports of PATH` (public symbols), \
`libraries` (external/internal package list), `callers of NAME` \
(same-file only), and `grep <pattern>` fallback. \
Returns 50-300 tokens of structured graph data instead of 10K+ from raw \
grep. Prefer this over native Grep for structural queries; use Grep for \
free-text search across files.",
        annotations(
            read_only_hint = true,
            destructive_hint = false,
            idempotent_hint = true,
            open_world_hint = false
        )
    )]
    pub async fn search_tool(
        &self,
        Parameters(req): Parameters<SearchRequest>,
    ) -> Result<Json<SearchResponse>, CallToolResult> {
        let graph = Arc::clone(&self.graph);
        let project_root = self.project_root.clone();
        // A second clone is needed: the first is moved into spawn_blocking,
        // the second is used after `.await` to relativize hit paths.
        let project_root_render = project_root.clone();
        let hits = tokio::task::spawn_blocking(move || {
            let g = graph.lock().expect("graph lock poisoned");
            dispatch(&g, &project_root, &req.query)
        })
        .await
        .map_err(|e| {
            to_error_result(&crate::error::BlastGuardError::Other(anyhow::anyhow!(
                "search join error: {e}"
            )))
        })?;
        let lines: Vec<String> = hits
            .iter()
            .map(|h| h.to_compact_line(&project_root_render))
            .collect();
        Ok(Json(SearchResponse { hits: lines }))
    }

    /// Apply one or more edits to a file with same-file cascade warnings.
    ///
    /// Returns `SIGNATURE` / `ASYNC_CHANGE` / `ORPHAN` / `INTERFACE_BREAK` warnings
    /// for callers in the same file plus their signatures. Multi-change edits
    /// roll back atomically on mid-sequence failure.
    ///
    /// Prefer over native Edit/Write when editing a signature or removing a
    /// public symbol — the cascade warnings surface same-file blast radius
    /// immediately. For cross-file blast radius, follow up with grep.
    #[tool(
        name = "apply_change",
        description = "Apply one or more edits to a file with same-file cascade warnings. \
Returns SIGNATURE / ASYNC_CHANGE / ORPHAN / INTERFACE_BREAK warnings \
for callers in the same file plus their signatures. Multi-change edits \
roll back atomically on mid-sequence failure. \
Prefer over native Edit/Write when editing a signature or removing a \
public symbol — the cascade warnings surface same-file blast radius \
immediately. For cross-file blast radius, follow up with grep.",
        annotations(
            read_only_hint = false,
            destructive_hint = true,
            idempotent_hint = false,
            open_world_hint = false
        )
    )]
    pub async fn apply_change_tool(
        &self,
        Parameters(req): Parameters<crate::edit::ApplyChangeRequest>,
    ) -> Result<Json<crate::edit::ApplyChangeResponse>, CallToolResult> {
        let graph = Arc::clone(&self.graph);
        let session = Arc::clone(&self.session);
        let project_root = self.project_root.clone();
        let result = tokio::task::spawn_blocking(move || {
            crate::mcp::apply_change::handle(&graph, &session, &project_root, &req)
        })
        .await
        .map_err(|e| {
            to_error_result(&crate::error::BlastGuardError::Other(anyhow::anyhow!(
                "apply_change join error: {e}"
            )))
        })?;
        match result {
            Ok(resp) => Ok(Json(resp)),
            Err(err) => Err(to_error_result(&err)),
        }
    }

    /// Run the project's test suite (auto-detects jest / vitest / pytest / cargo).
    ///
    /// Failures are annotated with `YOU MODIFIED X (N edits ago)` when a
    /// failing stack frame lands inside a symbol the session recently edited
    /// via `apply_change`. Use after an edit to tie regressions to recent work.
    #[tool(
        name = "run_tests",
        description = "Run the project's test suite (auto-detects jest / vitest / pytest / cargo). \
Failures are annotated with `YOU MODIFIED X (N edits ago)` when a \
failing stack frame lands inside a symbol the session recently edited \
via apply_change. Use after an edit to tie regressions to recent work.",
        annotations(
            read_only_hint = true,
            destructive_hint = false,
            idempotent_hint = true,
            open_world_hint = false
        )
    )]
    pub async fn run_tests_tool(
        &self,
        Parameters(req): Parameters<crate::runner::RunTestsRequest>,
    ) -> Result<Json<crate::runner::RunTestsResponse>, CallToolResult> {
        let graph = Arc::clone(&self.graph);
        let session = Arc::clone(&self.session);
        let project_root = self.project_root.clone();
        let result = tokio::task::spawn_blocking(move || {
            crate::mcp::run_tests::handle(&graph, &session, &project_root, &req)
        })
        .await
        .map_err(|e| {
            to_error_result(&crate::error::BlastGuardError::Other(anyhow::anyhow!(
                "run_tests join error: {e}"
            )))
        })?;
        match result {
            Ok(resp) => Ok(Json(resp)),
            Err(err) => Err(to_error_result(&err)),
        }
    }
}

// ── ServerHandler impl ────────────────────────────────────────────────────────

/// `#[tool_handler]` generates `call_tool` + `list_tools` methods that
/// delegate to `self.tool_router`. The additional async methods below handle
/// the `blastguard://status` resource.
#[tool_handler]
impl ServerHandler for BlastGuardServer {
    /// Advertise the server identity and capabilities to connecting clients.
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(
            ServerCapabilities::builder()
                .enable_tools()
                .enable_resources()
                .build(),
        )
        .with_server_info(Implementation::new(
            env!("CARGO_PKG_NAME"),
            env!("CARGO_PKG_VERSION"),
        ))
        .with_instructions(
            "BlastGuard tool routing — prefer these tools when the trigger matches:\n\
             • search: structural queries — 'callers of', 'imports of', 'outline of', \
             'tests for', 'find'/'where is', 'chain from X to Y'. Prefer over native Grep \
             when the intent is code structure, not raw text.\n\
             • apply_change: multi-file edits or any edit that could break callers — \
             signature changes, async flips, symbol renames/removals, interface changes. \
             Prefer over native Edit/Write when blast radius is unclear.\n\
             • run_tests: after any source edit in-session. Prefer over `bash pytest/cargo \
             test` because failures are annotated with 'YOU MODIFIED X (N edits ago)'.\n\
             Also exposes blastguard://status as a resource (index stats, last test run).\n\
             For trivial one-line fixes or plain-text searches, native tools are fine.",
        )
    }

    async fn list_resources(
        &self,
        _request: Option<PaginatedRequestParams>,
        _ctx: RequestContext<RoleServer>,
    ) -> Result<ListResourcesResult, ErrorData> {
        // `Resource = Annotated<RawResource>`; `no_annotation()` from `AnnotateAble`
        // wraps the raw resource with `annotations: None`.
        let resource = RawResource::new("blastguard://status", "Status")
            .with_description(
                "Compact project overview: graph node count, languages, recent edits, last test run.",
            )
            .with_mime_type("text/plain")
            .no_annotation();
        Ok(ListResourcesResult::with_all_items(vec![resource]))
    }

    async fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        _ctx: RequestContext<RoleServer>,
    ) -> Result<ReadResourceResult, ErrorData> {
        if request.uri == "blastguard://status" {
            let text = crate::mcp::status::render(&self.graph, &self.session, &self.project_root);
            return Ok(ReadResourceResult::new(vec![ResourceContents::text(
                text,
                "blastguard://status",
            )]));
        }
        Err(ErrorData::resource_not_found(
            format!("unknown resource: {}", request.uri),
            None,
        ))
    }
}

// ── Boot entry point ─────────────────────────────────────────────────────────

/// Async boot entry: load config, warm-start the index, stand up the rmcp
/// stdio server, and block until the MCP client disconnects.
///
/// # Errors
///
/// Propagates config load, indexer warm-start, or MCP handshake failures.
pub async fn run(project_root: &Path) -> anyhow::Result<()> {
    let config = Config::load(project_root).context("loading .blastguard/config.toml")?;

    let graph = indexer::warm_start(project_root).context("warm-starting index")?;

    let server = BlastGuardServer::new(graph, project_root.to_path_buf(), config);

    let watcher_handle =
        crate::index::watcher::spawn_watcher(project_root.to_path_buf(), Arc::clone(&server.graph))
            .context("spawning file watcher")?;
    tracing::info!("file watcher active at 100ms debounce");

    tracing::info!(
        project_root = %project_root.display(),
        version = env!("CARGO_PKG_VERSION"),
        "BlastGuard MCP server starting on stdio"
    );

    let transport = rmcp::transport::io::stdio();

    let service = server
        .serve(transport)
        .await
        .context("rmcp server initialization failed")?;

    tracing::info!("BlastGuard MCP server ready — awaiting client requests");

    service
        .waiting()
        .await
        .context("MCP service terminated with error")?;

    watcher_handle.abort();
    let _ = watcher_handle.await;

    tracing::info!("BlastGuard MCP server shutting down cleanly");
    Ok(())
}
